name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']
        strategy: [ 'highest' ]
        sf_version: ['']
        include:
            - php: 8.1
              strategy: 'lowest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: flex

      - name: Download dependencies
        uses: ramsey/composer-install@v2
        env:
            SYMFONY_REQUIRE: ${{ matrix.sf_version }}
        with:
          dependency-versions: ${{ matrix.strategy }}
          composer-options: --no-interaction --prefer-dist --optimize-autoloader

      - name: Install PHPUnit
        run: ./vendor/bin/simple-phpunit install

      - name: Run tests
        run: ./vendor/bin/simple-phpunit
